name: Secrets and Environment Variables
env:
  scope1: Workflow
  
  
on:
  push:
    branches: $GITHUB_REF
    
  workflow_dispatch:
    inputs:
      mytext:
        


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      scope2: Job
      
    steps:    
      - name: Display the Message
        env:
          scope3: Step
        run: |
          echo ${scope1}
          echo ${scope2}
          echo ${scope3}

